# Generated by Django 5.0.14 on 2026-05-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_profile_ecc_private_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ecc_private_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ecc_public_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
