# Generated by Django 5.0.14 on 2026-05-08 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_ecc_private_key_profile_ecc_public_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ecc_private_key',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ecc_public_key',
        ),
    ]
