# Generated by Django 5.0.14 on 2026-05-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_message_recipient_message_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='hmac',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
