# Generated by Django 5.0.14 on 2026-05-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_hmac_message_is_encrypted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='hmac',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
