# Generated by Django 5.0.14 on 2026-05-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_message_hmac'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
