# Generated by Django 5.0.14 on 2026-05-08 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_message_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='signature',
        ),
    ]
