# Generated by Django 5.0.14 on 2026-05-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_remove_message_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
